<?php echo $this->contentSaveForm->setAction($this->url()); ?>
<?php echo $this->contentSaveForm; ?>
<style>
    textarea#content {
        width: auto;
    }
</style>
<script type="text/javascript" src="<?php echo $this->basePath('js/jquery.form.js'); ?>"></script>
<script type="text/javascript">
    $(function()
    {
        $('#content-save-form').ajaxForm({
            dataType: 'json',
            succes: function(responseText,statusText,xhr, form){                
                $("#"+id).parent().find('.errors').remove();
                var els = form.find('input');
                els.each(function(el){
                    var name = el.attr('name');                    
                    if(responseText[name]){
                        el.parent().append(getErrorHtml(responseText[name], name));                       
                    }
                });
            }
        });
        
//        $("input").blur(function()
//        {
//            var formElementId = $(this).parent().prev().find('label').attr('for');
//            var url = $(this).parent('form').attr('action');
//            doValidation(formElementId, url);
//        });
    });
    function doValidation(id, url)
    {
        var data = {};
        $("input").each(function()
        {
            data[$(this).attr('name')] = $(this).val();
        });
        $.post(url,data,function(resp)
        {
            $("#"+id).parent().find('.errors').remove();
            $("#"+id).parent().append(getErrorHtml(resp[id], id));
        },'json');
    }
    function getErrorHtml(formErrors , id)
    {
        var o = '<ul id="errors-'+id+'" class="errors">';
        for(errorKey in formErrors)
        {
            o += '<li>' + formErrors[errorKey] + '</li>';
        }
        o += '</ul>';
        return o;
    }

</script>


