<script type="text/javascript">
    $(function(){
        var editor = new W4e.Page.Editor($('iframe'), {
            click: function(e){
                e.preventDefault();
                $('.dialog_content').dialog({
                    modal: true,
                    close: function(){
                        editor.change();
                    }
                });
            }
        });
    });
    var W4e = {};
    W4e = $.extend({
        'Page': {}
    },W4e);
    
    W4e.Page.Editor = function(frame, options){
        this.frame = frame;
        
        var self = this;
        this.options = $.extend({
            click: function(){},
            over: function(){
                self.getSlots().not($(this)).fadeTo(100, 0.7);                
                $(this).css({opacity: 1});    
            },
            out: function(){                
                self.getSlots().css({opacity: 1});                
            },
            click: function(){},
            load: function(){},
            change: function(){
                self.reload();
            },
            reload: function(){}
        }, options);
        
        frame.load(function(e){
            self.reinitialize();
            self.options.load(e);
        })
    }
    
    W4e.Page.Editor.prototype = {
        reinitialize: function(){
            var frame = this.getFrame();
            var document = this.getDocument();
            
            $(frame).width($(document).width());            
            $(frame).height($(document).height());
            
            var slots = this.getSlots();         
            slots.hover(this.options.over, this.options.out)
            .click(this.options.click);
        },
        getSlots: function()
        {
            var document = this.getDocument();
            return $('.hero-unit', document).add('.span4', document);            
        },
        getFrame: function(){
            return $(this.frame)[0];
        },        
        getWindow: function(){
            return this.getFrame().contentWindow || this.getFrame().window;
        },
        getDocument: function(){
            return this.getWindow().document || this.getFrame().contentDocument || this.getFrame().document;
        },
        change: function()
        {
            return this.options.change();
        },        
        reload: function(){
            if(this.options.reload() !==false){
                this.getWindow().location.reload();
            }
        },
        destroy: function(){
            var slots = this.getSlots();    
            slots.unbind('hover', this.options.over, this.options.out);            
            slots.unbind('click', this.options.click);
        }
    }
    
    (function( $ ){        
        $.plugin = function(name, object) {
            $.fn[name] = function(options) {
                var args = Array.prototype.slice.call(arguments, 1);
                return this.each(function() {
                    var instance = $.data(this, name);
                    if (instance) {
                        instance[options].apply(instance, args);
                    } else {
                        instance = $.data(this, name, new object(options, this));
                    }
                });
            };
        };

        var methods = {
            init : function( options ) {

                return this.each(function(){
         
                    var $this = $(this),
                    data = $this.data('page-editor');
                    if ( ! data ) {
                        $this.data('page-editor', {
                            editor: new W4e.Page.Editor($this, options)
                        });
                    }
                });
            },
            destroy : function( ) {

                return this.each(function(){
                    var $this = $(this);
                    var data = $this.data('page-editor');
                    if(data.editor){
                        data.editor.destroy();                        
                    }                    
                });
            }
        };


        $.fn.pageEditor = function( method ) {    
            if ( methods[method] ) {
                return methods[method].apply( this, Array.prototype.slice.call( arguments, 1 ));
            } else if ( typeof method === 'object' || ! method ) {
                return methods.init.apply( this, arguments );
            } else {
                $.error( 'Method ' +  method + ' does not exist on jQuery.Page.Editor' );
            }    
  
        };

    })( jQuery );
        
        

    
    
</script>
<div class="dialog_content">
    Test
</div>
<iframe src="<?php echo $this->url('home'); ?>" style="border: none; overflow: hidden; width: 100%;"></iframe>